### PR TITLE
clk: at91: allow setting PMC_AUDIOPINCK clock parents via DT

### PR DESCRIPTION
**Pull request by HiFiPhile**
Please add audio pin CLK_AUDIO output support. It resolves the issue I met here: https://www.microchip.com/forums/m1196141.aspx

### CODE REVIEW

**Review by claudiubeznea — COMMENTED** [review]
Looks good to me. Do you have have a device tree that uses this?

**Comment by HiFiPhile** [comment]
Here is my dtso:
```
&spi1 {
	#address-cells = <1>;
	#size-cells = <0>;
	pinctrl-names = "default";
	pinctrl-0 = <&pinctrl_mikrobus_spi>;
	status = "okay";

	spidev@0{
		compatible = "atmel,at91rm9200-spidev";
		reg = <0x0>;
		spi-max-frequency = <100000>;
	};

	spi_mcp3913: mcp3913@1{
		compatible = "microchip,mcp3913";
		reg = <0x1>;
		spi-max-frequency = <10000000>;
		pinctrl-names = "default";
		pinctrl-0 = <&pinctrl_mcp3913_io>;
		interrupt-parent = <&pioA>;
		interrupts = <PIN_PD2 IRQ_TYPE_LEVEL_LOW>;
		reset-gpios = <&pioA PIN_PB31 GPIO_ACTIVE_LOW>;
		device-addr = <1>;
		os-ratio = <256>;
		prescaler = <4>;
        clocks = <&pmc PMC_TYPE_CORE PMC_AUDIOPINCK>;
        assigned-clocks = <&pmc PMC_TYPE_CORE PMC_AUDIOPINCK>;
		assigned-clock-rates = <12288000>;
	};


};
```

**Comment by claudiubeznea** [comment]
Thanks! Could you also submit the changes in this PR to upstream?

**Comment by HiFiPhile** [comment]
Yes I just submitted the patch.

**Comment by claudiubeznea** [comment]
Nice! Thank you!

**Pull request closed without merging**
