### PR TITLE
Empty tristates do not show up in menuconfig and are not selectable

### PR DESCRIPTION
**Pull request by xbond879**
We need DMA and SSC options for our Atmel SoC sound card. Is there a reason the tristates are empty (that makes them unusable)?

### CODE REVIEW

**Comment by codrin989** [comment]
Are you using ASoC simple sound card driver? If not, you could select these options for your ASoC machine driver.
The main issue here is that SND_ATMEL_SOC_SSC is not a driver by itself. It is some sort of instance of drivers/misc/atmel-ssc.c and sound/soc/atmel/atmel_ssc_dai.c driver won't probe alone. This is because SSC supports other protocols as well, not just audio ones.

**Comment by xbond879** [comment]
We're using the seeed-voicecard driver (with codec wm8960):
https://github.com/respeaker/seeed-voicecard/blob/master/seeed-voicecard.c
which is pretty much based on the simple soundcard as far as I can see.

The code that we're really interested in is in the atmel-ssc.c file, functions
ssc_sound_dai_probe() and ssc_sound_dai_remove(), which are under CONFIG_SND_ATMEL_SOC_SSC defined condifion.

Do you think we should make some modifications in the seeed-voicecard driver instead of opting-in the CONFIG_SND_ATMEL_SOC_SSC definition for atmel-ssc.c ?

**Comment by codrin989** [comment]
Yes, I think that would be the best approach at this moment. Something like this https://github.com/linux4sam/linux-at91/blob/master/sound/soc/atmel/Kconfig#L54  . But if SSC works with the simple audio card, your changes are better.

**Comment by alexandrebelloni** [comment]
I don't think you can make the SSC work with simple-audio-card. However, what we would need is an atmel simple audio card driver handling the SSC that would replace most of the existing custom cards in the atmel folder. Freescale has that as they have a similar issue with the audmux. Until then, the proper solution is to make your sound card driver select the correct SSC option.

**Comment by xbond879** [comment]
Right, I see now!
However, the problem is we're building the wm8960 and seeed-soundcard drivers as a separate package in buildroot, so cannot select the option for Linux kernel. I can work on integrating this soundcard driver for linux-at91 properly and update this PR, but not sure it's allowed legally: respeaker seeed-voicecard is under GPLv3 license:
https://github.com/respeaker/seeed-voicecard/blob/master/LICENSE
while linux-at91 is GPLv2. I'm not an expert about licensing, so if you can confirm if that's allowed or not - it could help a lot =)

**Comment by alexandrebelloni** [comment]
My point of view (but I am not a lawyer) is that they can't license their kernel module with only a CPLv2 incompatible license because the module is a derived work of the kernel. You'll see that https://github.com/respeaker/seeed-voicecard/blob/master/seeed-voicecard.c has MODULE_LICENSE("GPL v2"); and thte header states GPL v2 too.

**Comment by peda-r** [comment]
I have successfully used the SSC with the simple-audio-card driver.

You need to add this (or similar) to the dts:
&ssc0 {
        #sound-dai-cells = <0>;
        status = "okay";
};

The #sound-dai-cells property triggers the SSC to make itself available to the sound subsystem.

You also need to have one of the atmel audio cards enabled in the config so that the mentioned SSC config option is selected. This last bit is a bit backwards, there should be some cleaner way to select what you want, but...

**Comment by xbond879** [comment]
Ok, I made some experiments on the simple-audio-card driver and almost made it work for us instead of the seeed driver. The only issue I have right now is: while playing sound from wav file it's twice faster and while recording the output file - it is twice slower than it should be.
It's likely the clock frequencies are not getting applied properly. I'll try to figure it out and likely will move forward with a local buildroot patch for the codec driver, which is not needed in main linux-at91 repository.

**Comment by alexandrebelloni** [comment]
If you are using the programmable clock of the sama5d2, did you try that patch?
https://patchwork.kernel.org/patch/10857367/

**Comment by xbond879** [comment]
We're using sama5d4-explained, but I'll check the patch, thank you.

**Comment by xbond879** [comment]
So, to make the kernel driver working I had to change the code of wm8960.c in 3 places:
- lines 1290 and 1404 - both places set clk_id to hardcoded WM8960_SYSCLK_PLL, (functions wm8960_set_dai_sysclk and wm8960_i2c_probe)
- line 1305 - set wm8960->freq_in to hardcoded 24000000 (function wm8960_set_dai_sysclk)

These changes are copied from seeed's version of the driver, but I really do not like this kind of hard-code there.
While for wm8960_i2c_probe I can add some option to device-table and set sys-clock to WM8960_SYSCLK_PLL (which is 1) if it's set, I'm still getting clk_id equals WM8960_SYSCLK_MCLK (0) in the wm8960_set_dai_sysclk function. That's the place I'm not getting - what's the proper way to control it?
Also, I've tried to set frequency from dtb, but no luck so far...

If you could help me with that by pointing to the right direction - I'd really appreciate your help! Regarding the original PR - it's obviously not needed =)

**Comment by codrin989** [comment]
wm8960 codec is not compatible with simple-audio-card. You can't change/configure the system clock if its clk_id is not 0 in simple-audio-card. So, for now, you have 2 options:
1. use seeed-voicecard (or other sound machine driver used for your wm8960 only) and use snd_soc_dai_set_sysclk() to configure wm8960;
2. Change the defaults for wm8960 codec, as you did;

Regarding your pull request, if SSC works with the simple-audio-card, from my point of view, we should be able to select SSC in menuconfig, with some mentions:
 - SND_ATMEL_SOC_SSC should depend on ATMEL_SSC;
 - SND_ATMEL_SOC_SSC_DMA and SND_ATMEL_SOC_SSC_PDC don't make sense to be selected by the user, but by the platform;

**Comment by peda-r** [comment]
> if SSC works with the simple-audio-card

It does since v4.11, which has
e8314d7d53c8 ("misc: atmel-ssc: register as sound DAI if #sound-dai-cells is present")

**Comment by xbond879** [comment]
thank you! I'll prepare the updated PR and will move forward with a patch for wm8960 driver applied from buildroot

**Comment by codrin989** [comment]
Thank you for the update. We should still find a way to select SND_ATMEL_SOC_SSC_DMA or SND_ATMEL_SOC_SSC_PDC based on platform. @alexandrebelloni could you please share your thoughts on this?

@peda-r I was just implying that I never tested it with simple-audio-card. I am glad that it works. Thank you for your patch. We can now remove the machine code specific for SSC, maybe even remove the machine driver entirely.

**Comment by alexandrebelloni** [comment]
This is going to be fixed upstream using:
https://lore.kernel.org/lkml/233d5461f4448df151755de7b69a0cd3ad310d5c.1566677788.git.mirq-linux@rere.qmqm.pl/

**Comment by noglitch** [comment]
Gentlemen (@codrin989 , @xbond879 , ...), After this detailed discussion, can I close this PR now?

**Comment by cristibirsan** [comment]
I will close this as the patch mentioned and a fix for it was accepted upstream and is present in linux-5.10-at91.

**Pull request closed without merging**
